### ISSUE TITLE
License

### ISSUE THREAD

**Issue by andrew-mi** [cansik/ArtNet3DotNet#1]
Hi @cansik,
The library works well; I just wanted to ask if a license could be made/clarified.
a. Am I allowed to use this in other open source projects with credit given?
b. Am I allowed to use this in commercial projects with credit given?

Thanks,
Andrew M

**Comment by cansik** [comment]
To be honest, I would not recommend to use my library because it is not under active development and not finished at all. Isn't there another one which is more complete?
But if you would like to use it (open source and commercial), go for it.

 I've added the MIT license, which should give you all the rights.

**Comment by andrew-mi** [comment]
@cansik Thanks
